AWSTemplateFormatVersion: 2010-09-09

Description:  Continuous deployment infrastructure for S3 Bucket website-pipeline

Parameters:
  BranchName:
    Description: GitHub branch name
    Type: String
    Default: master
  RepositoryName:
    Description: GitHub repository name
    Type: String
    Default: website-pipeline
  GitHubOwner:
      Type: String
      Default: donhenton
  TargetBucketName:
    Description: final S3 bucket destination
    Type: String
    Default: com.awsdhenton.testing



Outputs:
  PipelineConsoleUrl:
    Description: Console URL for the CodePipeline pipleine
    Export:
      Name: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - !Ref 'AWS::Region'
          - PipelineCloneUrl
    Value: !Join
      - ''
      - - 'https://'
        - !Ref 'AWS::Region'
        - '.console.aws.amazon.com/codepipeline/home?region='
        - !Ref 'AWS::Region'
        - '#/view/'
        - !Ref 'AWS::StackName'
  ArtifactsBucket:
    Description: S3 bucket used for artifacts
    Export:
      Name: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - !Ref 'AWS::Region'
          - ArtifactsBucket
    Value: !Ref ArtifactsBucket

Resources:

  GithubOauthToken:
    Type: Custom::GetSecureSSMFunction
    Properties:
      ServiceToken:
        !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getSecureSSM"
      ParameterName: "/github/oauth"
  GithubProjectSecret:
    Type: Custom::GetSecureSSMFunction
    Properties:
      ServiceToken:
        !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getSecureSSM"
      ParameterName: !Sub 
        - /github/${RepValue}/secret
        - {RepValue: !Ref RepositoryName}



  CloudFormationTrustRole:
    Description: Creating service role in IAM for AWS CloudFormation
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - cloudformation.amazonaws.com
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - iam:CreateRole
            - iam:AttachRolePolicy
            - iam:PutRolePolicy
            - iam:PassRole
            - iam:DetachRolePolicy
            - iam:ListRolePolicies
            - iam:GetRole
            - iam:DeleteRolePolicy
            - iam:UpdateRoleDescription
            - iam:ListRoles
            - iam:DeleteRole
            - iam:GetRolePolicy
            - iam:CreateInstanceProfile
            - iam:AddRoleToInstanceProfile
            - iam:DeleteInstanceProfile
            - iam:GetInstanceProfile
            - iam:ListInstanceProfiles
            - iam:ListInstanceProfilesForRole
            - iam:RemoveRoleFromInstanceProfile
            Effect: Allow
            Resource:
            - !Sub "arn:aws:iam::*:role/${AWS::StackName}*"
            - !Sub "arn:aws:iam::*:instance-profile/${AWS::StackName}*"
          - Action:
            - ssm:GetParameters
            - autoscaling:*
            - ec2:*
            - codedeploy:*
            - elasticloadbalancing:*
            Effect: Allow
            Resource: '*'
        PolicyName: !Join
          - '-'
          -  - !Ref 'AWS::StackName'
             - CloudFormationRolePolicy
      RoleName: !Join
        - '-'
        -  - !Ref 'AWS::StackName'
           - CloudFormation
    Type: AWS::IAM::Role
  CodeBuildPolicy:
    Description: Setting IAM policy for service role for CodeBuild
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Effect: Allow
          Resource: '*'
        - Action:
          - s3:PutObject
          - s3:GetObject
          - s3:GetObjectVersion
          Effect: Allow
          Resource:
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref 'ArtifactsBucket'
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref 'ArtifactsBucket'
              - /*
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref 'CacheBucket'
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref 'CacheBucket'
              - /*
      
        - Action:
          - kms:GenerateDataKey*
          - kms:Encrypt
          - kms:Decrypt
          Effect: Allow
          Resource:
          - !Join
            - ':'
            - - arn:aws:kms
              - !Ref 'AWS::Region'
              - !Ref 'AWS::AccountId'
              - !Join
                - /
                - - alias
                  - aws/s3
      PolicyName: !Join
        - '-'
        -  - !Ref 'AWS::StackName'
           - CodeBuildPolicy
      Roles:
      - !Ref 'CodeBuildRole'
    Type: AWS::IAM::Policy
  CodePipelineTrustRole:
    Description: Creating service role in IAM for AWS CodePipeline
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - codepipeline.amazonaws.com
          Sid: 1
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:GetBucketVersioning
            - s3:PutObject
            Effect: Allow
            Resource:
            - !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref 'ArtifactsBucket'
            - !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref 'ArtifactsBucket'
                - /*
          - Action:
            - codebuild:StartBuild
            - codebuild:BatchGetBuilds
            - codebuild:StopBuild
            Effect: Allow
            Resource:
          #  - !GetAtt 'CodeBuildProject.Arn'
             - "*"
          - Action:
            - codedeploy:CreateDeployment
            - codedeploy:GetApplicationRevision
            - codedeploy:GetDeployment
            - codedeploy:GetDeploymentConfig
            - codedeploy:RegisterApplicationRevision
            Effect: Allow
            Resource:
            - !Join
              - ':'
              - - arn
                - aws
                - codedeploy
                - !Ref 'AWS::Region'
                - !Ref 'AWS::AccountId'
                - deploymentgroup
                - !Join
                  - ''
                  - - !Ref 'AWS::StackName'
                    - '*'
            - !Join
              - ':'
              - - arn
                - aws
                - codedeploy
                - !Ref 'AWS::Region'
                - !Ref 'AWS::AccountId'
                - application
                - !Join
                  - ''
                  - - !Ref 'AWS::StackName'
                    - '*'
            - !Join
              - ':'
              - - arn
                - aws
                - codedeploy
                - !Ref 'AWS::Region'
                - !Ref 'AWS::AccountId'
                - deploymentconfig
                - '*'
          - Action:
            - cloudformation:DescribeStacks
            - cloudformation:DescribeChangeSet
            - cloudformation:CreateChangeSet
            - cloudformation:DeleteChangeSet
            - cloudformation:ExecuteChangeSet
            Effect: Allow
            Resource:
            - !Join
              - ':'
              - - arn
                - aws
                - cloudformation
                - !Ref 'AWS::Region'
                - !Ref 'AWS::AccountId'
                - !Join
                  - /
                  - - stack
                    - !Join
                      - '-'
                      -  - !Ref 'AWS::StackName'
                         - '*'
          - Action:
            - iam:PassRole
            Effect: Allow
            Resource:
            - !GetAtt
              - CloudFormationTrustRole
              - Arn
        PolicyName: !Join
          - '-'
          - - !Ref 'AWS::StackName'
            - CodePipelineRolePolicy
      RoleName: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - CodePipeline
    Type: AWS::IAM::Role
  ArtifactBucketPolicy:
    Description: Setting Amazon S3 bucket policy for AWS CodePipeline access
    Properties:
      Bucket: !Ref 'ArtifactsBucket'
      PolicyDocument:
        Id: SSEAndSSLPolicy
        Statement:
        - Action:
          - s3:GetObject
          - s3:GetObjectVersion
          - s3:GetBucketVersioning
          Condition:
            Bool:
              aws:SecureTransport: false
          Effect: Allow
          Principal:
            AWS:
            - !GetAtt
              - CodePipelineTrustRole
              - Arn
            - !GetAtt
              - CodeBuildRole
              - Arn
            - !GetAtt
              - CloudFormationTrustRole
              - Arn
          Resource:
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref 'ArtifactsBucket'
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref 'ArtifactsBucket'
              - /*
          Sid: WhitelistedGet
        - Action:
          - s3:PutObject
          Effect: Allow
          Principal:
            AWS:
            - !GetAtt
              - CodePipelineTrustRole
              - Arn
            - !GetAtt
              - CodeBuildRole
              - Arn
          Resource:
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref 'ArtifactsBucket'
          - !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref 'ArtifactsBucket'
              - /*
          Sid: WhitelistedPut
        Version: 2012-10-17
    Type: AWS::S3::BucketPolicy
  ArtifactsBucket:
    DeletionPolicy: Delete
    Description: Creating Amazon S3 bucket for AWS CodePipeline and CodeBuild artifacts
    Properties:
      Tags:
      - Key: Name
        Value: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - ArtifactsBucket
      VersioningConfiguration:
        Status: Enabled
    Type: AWS::S3::Bucket
  CacheBucket:
    DeletionPolicy: Delete
    Description: Creating Amazon S3 bucket for CodeBuild caching
    Properties:
      Tags:
      - Key: Name
        Value: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - CacheBucket
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Status: Enabled
    Type: AWS::S3::Bucket
  CodeBuildRole:
    Description: Creating service role in IAM for AWS CodeBuild
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
      Path: /
      RoleName: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - CodeBuild
    Type: AWS::IAM::Role

  AppPipelineWebhook:
    Type: 'AWS::CodePipeline::Webhook'
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Sub '${GithubProjectSecret.Value}'
      Filters:
        - JsonPath: $.ref
          MatchEquals: 'refs/heads/{Branch}'
      TargetPipeline: !Ref AppPipeline
      TargetAction: SourceAction
      Name: !Sub 'AppPipelineWebhook-${RepositoryName}'
      TargetPipelineVersion: !GetAtt 
        - AppPipeline
        - Version
      RegisterWithThirdParty: true
  AppPipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: !Sub 
        - ${RepValue}-deploy-pipeline
        - {RepValue: !Ref RepositoryName}
      RoleArn: !GetAtt 
        - CodePipelineTrustRole
        - Arn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref RepositoryName
                Branch: !Ref BranchName
                OAuthToken: !Sub '${GithubOauthToken.Value}'
                PollForSourceChanges: false
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: S3
              Configuration:
                BucketName: !Ref TargetBucketName
                Extract: true
              InputArtifacts:
                - Name: SourceOutput
              RunOrder: 2    
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactsBucket